id = "unofficial-codeium-extension"
name = "Unofficial Codeium Extension"
version = "0.0.1"
schema_version = 1
authors = ["Kovacs Balint-Hunor <kovacsbalinthunor13@gmail.com>"]
description = "Integrates Codeium with Zed"
repository = "https://github.com/MemerGamer/unofficial-codeium-zed-extension"

[slash_commands.codeium-auth]
description = "Opens Codeium"
requires_argument = false

[slash_commands.codeium-save-token]
description = "Saves Codeium token"
requires_argument = true

